"""baseline schema

Revision ID: 228478a4578e
Revises:
Create Date: 2026-08-26 14:43:49.923343

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "228478a4578e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calls",
        sa.Column("call_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=255), nullable=False),
        sa.Column("agent_id", sa.String(length=255), nullable=False),
        sa.Column("provider_call_id", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_reason", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.CheckConstraint("status IN ('active', 'completed', 'failed')", name="ck_calls_status"),
        sa.PrimaryKeyConstraint("call_id"),
    )
    op.create_index("idx_calls_tenant_started", "calls", ["tenant_id", "started_at"], unique=False)
    op.create_index(op.f("ix_calls_provider_call_id"), "calls", ["provider_call_id"], unique=False)
    op.create_index(op.f("ix_calls_tenant_id"), "calls", ["tenant_id"], unique=False)
    op.create_table(
        "clients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=True),
        sa.Column("plan", sa.String(length=50), server_default="starter", nullable=True),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=True),
        sa.Column("contact_email", sa.String(length=255), nullable=True),
        sa.Column("contact_phone", sa.String(length=50), nullable=True),
        sa.Column("api_limit", sa.Integer(), server_default="100", nullable=True),
        sa.Column("max_concurrent_calls", sa.Integer(), server_default="10", nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.CheckConstraint("plan IN ('starter', 'pro', 'enterprise')", name="ck_clients_plan"),
        sa.CheckConstraint(
            "status IN ('active', 'suspended', 'inactive')", name="ck_clients_status"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_clients_id"), "clients", ["id"], unique=False)
    op.create_index(op.f("ix_clients_slug"), "clients", ["slug"], unique=True)
    op.create_table(
        "phone_number_routes",
        sa.Column("number", sa.String(length=20), nullable=False),
        sa.Column("tenant_id", sa.String(length=255), nullable=False),
        sa.Column("agent_id", sa.String(length=255), nullable=False),
        sa.Column("provider", sa.String(length=50), server_default="exotel", nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("number"),
    )
    op.create_table(
        "admin_users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("role", sa.String(length=50), server_default="agent", nullable=True),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.CheckConstraint(
            "role IN ('super_admin', 'tenant_admin', 'agent')", name="ck_admin_users_role"
        ),
        sa.CheckConstraint("status IN ('active', 'suspended')", name="ck_admin_users_status"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["clients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_admin_users_email"), "admin_users", ["email"], unique=True)
    op.create_table(
        "call_events",
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("call_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["call_id"], ["calls.call_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        "idx_call_events_tenant_call", "call_events", ["tenant_id", "call_id"], unique=False
    )
    op.create_table(
        "call_turns",
        sa.Column("turn_id", sa.String(length=36), nullable=False),
        sa.Column("call_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=255), nullable=False),
        sa.Column("speaker", sa.String(length=20), nullable=False),
        sa.Column("language_code", sa.String(length=10), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("speaker IN ('caller', 'agent')", name="ck_call_turns_speaker"),
        sa.ForeignKeyConstraint(["call_id"], ["calls.call_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("turn_id"),
    )
    op.create_index(
        "idx_call_turns_tenant_call", "call_turns", ["tenant_id", "call_id"], unique=False
    )
    op.create_table(
        "audit_logs",
        sa.Column("audit_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=255), nullable=True),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("before_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["admin_users.id"],
        ),
        sa.PrimaryKeyConstraint("audit_id"),
    )
    op.create_index(
        "idx_audit_logs_tenant_occurred", "audit_logs", ["tenant_id", "occurred_at"], unique=False
    )
    # NOTE: autogenerate also proposed dropping `users` — that table belongs to
    # the legacy app/ module (app/models/user.py), not services/api/src/models.py.
    # It is intentionally left alone; app/ manages its own schema via create_all
    # until it is retired.
    #
    # `call_requests` (services/api/src/models.py::Caller) — this migration was
    # originally autogenerated by diffing against a database that already had
    # this table from the legacy app/'s create_all(), so the original version
    # here only ALTERed it (add_column/create_foreign_key) instead of creating
    # it. That made `alembic upgrade head` fail with UndefinedTableError
    # against a genuinely fresh database. Fixed by having this migration own
    # full table creation, matching the current Caller model exactly.
    op.create_table(
        "call_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_name", sa.String(), nullable=True),
        sa.Column("phone_number", sa.String(), nullable=True),
        sa.Column("hotel_name", sa.String(), nullable=True),
        sa.Column("check_in_date", sa.String(), nullable=True),
        sa.Column("check_out_date", sa.String(), nullable=True),
        sa.Column("client_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["client_id"], ["clients.id"], name="fk_call_requests_client_id_clients"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_call_requests_id"), "call_requests", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_call_requests_id"), table_name="call_requests")
    op.drop_table("call_requests")
    op.drop_index("idx_audit_logs_tenant_occurred", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index("idx_call_turns_tenant_call", table_name="call_turns")
    op.drop_table("call_turns")
    op.drop_index("idx_call_events_tenant_call", table_name="call_events")
    op.drop_table("call_events")
    op.drop_index(op.f("ix_admin_users_email"), table_name="admin_users")
    op.drop_table("admin_users")
    op.drop_table("phone_number_routes")
    op.drop_index(op.f("ix_clients_slug"), table_name="clients")
    op.drop_index(op.f("ix_clients_id"), table_name="clients")
    op.drop_table("clients")
    op.drop_index(op.f("ix_calls_tenant_id"), table_name="calls")
    op.drop_index(op.f("ix_calls_provider_call_id"), table_name="calls")
    op.drop_index("idx_calls_tenant_started", table_name="calls")
    op.drop_table("calls")
    # ### end Alembic commands ###
